# Credits @rencprx 
# dont't remove credit
# you noob:v
# recode by @ikhsanntarjo

version: "3.9"
services:
  worker:
    build: .
    environment:
      STRING_SESSION1: $STRING_SESSION1
      STRING_SESSION2: $STRING_SESSION2
      STRING_SESSION3: $STRING_SESSION3
      STRING_SESSION4: $STRING_SESSION4
      LOG_SESSION: $LOG_SESSION
      API_ID: $API_ID
      API_HASH: $API_HASH
      MONGO_DB_URI: $MONGO_DB_URI
      LOG_GROUP_ID: $LOG_GROUP_ID
      BOT_TOKEN: $BOT_TOKEN
      MUSIC_BOT_NAME: $MUSIC_BOT_NAME
      SUPPORT_CHANNEL: $SUPPORT_CHANNEL
      SUPPORT_GROUP: $SUPPORT_GROUP
      OWNER_ID: $OWNER_ID
      DURATION_LIMIT: $DURATION_LIMIT
      UPSTREAM_REPO: $UPSTREAM_REPO
      UPSTREAM_BRANCH: $UPSTREAM_BRANCH
      ASSISTANT_PREFIX: $ASSISTANT_PREFIX
      SUDO_USERS: $SUDO_USERS
